spring:
  datasource:
    password: Pass1234
    username: postgres
    url: jdbc:postgresql://localhost:5432/customer
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yml
server:
  port: 8091